@ECHO OFF

REM create bin directory if it doesn't exist
if not exist ..\bin mkdir ..\bin

REM delete output from previous run
if exist ACTUAL.TXT del ACTUAL.TXT

REM compile the code into the bin folder
REM Use "for" loop to compile all .java files recursively
for /r ..\src\main\java %%f in (*.java) do (
    javac -cp ..\src\main\java -Xlint:none -d ..\bin "%%f"
)
IF ERRORLEVEL 1 (
    echo ********** BUILD FAILURE **********
    exit /b 1
)

REM run the program, feed commands from input.txt file and redirect the output to the ACTUAL.TXT
REM Use fully qualified class name (package + class name)
java -classpath ..\bin homura.homura < input.txt > ACTUAL.TXT

REM convert ACTUAL.TXT and EXPECTED.TXT to UNIX format
REM Windows doesn't have a direct dos2unix equivalent; you can use PowerShell if needed.
powershell -Command "(Get-Content ACTUAL.TXT) -replace \"`r`n\", \"`n\" | Set-Content ACTUAL.TXT"
powershell -Command "(Get-Content EXPECTED.TXT) -replace \"`r`n\", \"`n\" | Set-Content EXPECTED.TXT"

REM compare the output to the expected output
FC ACTUAL.TXT EXPECTED.TXT
@REM IF ERRORLEVEL 1 (
@REM     echo Test result: FAILED
@REM     exit /b 1
@REM ) ELSE (
@REM     echo Test result: PASSED
@REM     exit /b 0
@REM )

REM delete HomuraTodos.txt without errors if it doesn't exist
if exist HomuraTodos.txt del "HomuraTodos.txt"




















REM How to put a multiline comment in .bat files inspired by
REM https://stackoverflow.com/questions/8526946/
REM commenting-multiple-lines-in-dos-batch-file

REM Explanation from ChatGPT on how this works
goto multiline_comment
Recursive Compilation:

Used a for /r loop to compile all .java files under ..\src\main\java recursively, respecting the package structure.
The %%f represents each .java file found.
Running the Program:

The fully qualified class name (e.g., homura.homura) is specified when running the program. This includes the package name.
Unix Format Conversion:

Since Windows batch scripts don't have a direct dos2unix equivalent, I used PowerShell commands to convert CRLF line endings (\r\n) to LF (\n) in the files.
Silent Deletion:

The del command for HomuraTodos.txt ensures it does not raise an error if the file doesn't exist.
:multiline_comment

REM Code above generated by ChatGPT with the following query:
goto multiline_comment
Hi! I also have a batch file that serves the same purpose as the shell script above, and I want to also fix it to run properly as well. How can I fix it? Here is the batch file

```
@ECHO OFF

REM create bin directory if it doesn't exist
if not exist ..\bin mkdir ..\bin

REM delete output from previous run
if exist ACTUAL.TXT del ACTUAL.TXT

REM compile the code into the bin folder
javac  -cp ..\src\main\java -Xlint:none -d ..\bin ..\src\main\java\*.java
IF ERRORLEVEL 1 (
    echo ********** BUILD FAILURE **********
    exit /b 1
)
REM no error here, errorlevel == 0

REM run the program, feed commands from input.txt file and redirect the output to the ACTUAL.TXT
java -classpath ..\bin homura < input.txt > ACTUAL.TXT

REM compare the output to the expected output
FC ACTUAL.TXT EXPECTED.TXT

REM How to delete a file inspired by
REM https://stackoverflow.com/questions/13764103/batch-script-to-delete-files
del "HomuraTodos.txt"
```
:multiline_comment








































REM OLD VERSION OF CODE BELOW ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
goto multiline_comment
@ECHO OFF

REM create bin directory if it doesn't exist
if not exist ..\bin mkdir ..\bin

REM delete output from previous run
if exist ACTUAL.TXT del ACTUAL.TXT

REM compile the code into the bin folder
javac  -cp ..\src\main\java -Xlint:none -d ..\bin ..\src\main\java\*.java
IF ERRORLEVEL 1 (
    echo ********** BUILD FAILURE **********
    exit /b 1
)
REM no error here, errorlevel == 0

REM run the program, feed commands from input.txt file and redirect the output to the ACTUAL.TXT
java -classpath ..\bin homura < input.txt > ACTUAL.TXT

REM compare the output to the expected output
FC ACTUAL.TXT EXPECTED.TXT

REM How to delete a file inspired by
REM https://stackoverflow.com/questions/13764103/batch-script-to-delete-files
del "HomuraTodos.txt"
:multiline_comment
