#Largely copied from
#https://github.com/se-edu/duke/blob/full-template/.github/workflows/gradle.yml

name: Java CI

on: #[push, pull_request]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up repository
        uses: actions/checkout@master
